theme: jekyll-theme-minimal
title:  ğŸ’»âœ’ï¸ğŸ“„ 
description: |+
      Israel Martinez Hernandez's CV.
      Senior Research Associate.
      Dept Mathematics and Statistics. 
      Lancaster University, UK.


