theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„
description: Israel Martinez Hernandez's CV

author:
  name     : "Israel Martinez Hernandez"
  avatar   : "/assets/images/bio-photo.jpg"
  location : "Lancaster, UK"
