theme: jekyll-theme-minimal
title:  ðŸ’»âœ’ï¸ðŸ“„ 
description: >
      Israel Martinez Hernandez's CV
      Senior Research Associate 
      Department of Mathematics and Statistics 
      Lancaster University, UK 


