theme: jekyll-theme-minimal
title:  ðŸ’»âœ’ï¸ðŸ“„ 
description: >
      Israel Martinez Hernandez's CV \n
      Senior Research Associate \n
      \n
      Department of Mathematics and Statistics 
      Lancaster University, UK 


