theme: jekyll-theme-minimal
title:  ğŸ’»âœ’ï¸ğŸ“„ 
description: |\n
      ..Israel Martinez Hernandez's CV, \n
      ..Senior Research Associate, \n
      ..Dept Mathematics and Statistics, \n
      ..Lancaster University, UK.


